# CircleCI configuration file
version: 2.1

jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
        fingerprints:
          - "SHA256:W9nNeqH1ObudeY8OFYNrBywL2jAc5uLvKb4EMPnLj5A"
  build:
    docker:
     - image: cimg/node:16.20.1
    steps:
      
      - run: echo "Say hello to YAML!"
      - run: npm -v
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: chmod +x scripts/deploy.sh
      - run:
          name: run deploy to github pages
          command: ./scripts/deploy.sh
