# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
     - image: cimg/node:20.5
    steps:
      - run: echo "Say hello to YAML!"
      - run: npm -v
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build