# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
     - image: circleci/node:20
    steps:
      - run: echo "Say hello to YAML!"
      - run: npm -v
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: vite build